//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tanks.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tanks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Apple {
            get {
                object obj = ResourceManager.GetObject("Apple", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FireTank1 {
            get {
                object obj = ResourceManager.GetObject("FireTank1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FireTank2 {
            get {
                object obj = ResourceManager.GetObject("FireTank2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FireTank3 {
            get {
                object obj = ResourceManager.GetObject("FireTank3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FireTank4 {
            get {
                object obj = ResourceManager.GetObject("FireTank4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FireTank5 {
            get {
                object obj = ResourceManager.GetObject("FireTank5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FireTank6 {
            get {
                object obj = ResourceManager.GetObject("FireTank6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg_10 {
            get {
                object obj = ResourceManager.GetObject("HunterImg_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg_10I {
            get {
                object obj = ResourceManager.GetObject("HunterImg_10I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg_10II {
            get {
                object obj = ResourceManager.GetObject("HunterImg_10II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg_10III {
            get {
                object obj = ResourceManager.GetObject("HunterImg_10III", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg_10IV {
            get {
                object obj = ResourceManager.GetObject("HunterImg_10IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg0_1 {
            get {
                object obj = ResourceManager.GetObject("HunterImg0_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg0_1I {
            get {
                object obj = ResourceManager.GetObject("HunterImg0_1I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg0_1II {
            get {
                object obj = ResourceManager.GetObject("HunterImg0_1II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg0_1III {
            get {
                object obj = ResourceManager.GetObject("HunterImg0_1III", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg0_1IV {
            get {
                object obj = ResourceManager.GetObject("HunterImg0_1IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg01 {
            get {
                object obj = ResourceManager.GetObject("HunterImg01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg01I {
            get {
                object obj = ResourceManager.GetObject("HunterImg01I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg01II {
            get {
                object obj = ResourceManager.GetObject("HunterImg01II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg01III {
            get {
                object obj = ResourceManager.GetObject("HunterImg01III", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg01IV {
            get {
                object obj = ResourceManager.GetObject("HunterImg01IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg10 {
            get {
                object obj = ResourceManager.GetObject("HunterImg10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg10I {
            get {
                object obj = ResourceManager.GetObject("HunterImg10I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg10II {
            get {
                object obj = ResourceManager.GetObject("HunterImg10II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg10III {
            get {
                object obj = ResourceManager.GetObject("HunterImg10III", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap HunterImg10IV {
            get {
                object obj = ResourceManager.GetObject("HunterImg10IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Info {
            get {
                object obj = ResourceManager.GetObject("Info", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NewGame {
            get {
                object obj = ResourceManager.GetObject("NewGame", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap NoSound {
            get {
                object obj = ResourceManager.GetObject("NoSound", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg_10 {
            get {
                object obj = ResourceManager.GetObject("PackmanImg_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg_10I {
            get {
                object obj = ResourceManager.GetObject("PackmanImg_10I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg_10II {
            get {
                object obj = ResourceManager.GetObject("PackmanImg_10II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg_10III {
            get {
                object obj = ResourceManager.GetObject("PackmanImg_10III", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg_10IV {
            get {
                object obj = ResourceManager.GetObject("PackmanImg_10IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg0_1 {
            get {
                object obj = ResourceManager.GetObject("PackmanImg0_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg0_1I {
            get {
                object obj = ResourceManager.GetObject("PackmanImg0_1I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg0_1II {
            get {
                object obj = ResourceManager.GetObject("PackmanImg0_1II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg0_1III {
            get {
                object obj = ResourceManager.GetObject("PackmanImg0_1III", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg0_1IV {
            get {
                object obj = ResourceManager.GetObject("PackmanImg0_1IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg01 {
            get {
                object obj = ResourceManager.GetObject("PackmanImg01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg01I {
            get {
                object obj = ResourceManager.GetObject("PackmanImg01I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg01II {
            get {
                object obj = ResourceManager.GetObject("PackmanImg01II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg01III {
            get {
                object obj = ResourceManager.GetObject("PackmanImg01III", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg01IV {
            get {
                object obj = ResourceManager.GetObject("PackmanImg01IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg10 {
            get {
                object obj = ResourceManager.GetObject("PackmanImg10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg10I {
            get {
                object obj = ResourceManager.GetObject("PackmanImg10I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg10II {
            get {
                object obj = ResourceManager.GetObject("PackmanImg10II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg10III {
            get {
                object obj = ResourceManager.GetObject("PackmanImg10III", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PackmanImg10IV {
            get {
                object obj = ResourceManager.GetObject("PackmanImg10IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PauseButton {
            get {
                object obj = ResourceManager.GetObject("PauseButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PlayButton {
            get {
                object obj = ResourceManager.GetObject("PlayButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Projectile_10 {
            get {
                object obj = ResourceManager.GetObject("Projectile_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Projectile0_1 {
            get {
                object obj = ResourceManager.GetObject("Projectile0_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Projectile01 {
            get {
                object obj = ResourceManager.GetObject("Projectile01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Projectile10 {
            get {
                object obj = ResourceManager.GetObject("Projectile10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SoundOn {
            get {
                object obj = ResourceManager.GetObject("SoundOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg_10 {
            get {
                object obj = ResourceManager.GetObject("TankImg_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg_10I {
            get {
                object obj = ResourceManager.GetObject("TankImg_10I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg_10II {
            get {
                object obj = ResourceManager.GetObject("TankImg_10II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg_10III {
            get {
                object obj = ResourceManager.GetObject("TankImg_10III", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg_10IV {
            get {
                object obj = ResourceManager.GetObject("TankImg_10IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg0_1 {
            get {
                object obj = ResourceManager.GetObject("TankImg0_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg0_1I {
            get {
                object obj = ResourceManager.GetObject("TankImg0_1I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg0_1II {
            get {
                object obj = ResourceManager.GetObject("TankImg0_1II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg0_1III {
            get {
                object obj = ResourceManager.GetObject("TankImg0_1III", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg0_1IV {
            get {
                object obj = ResourceManager.GetObject("TankImg0_1IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg01 {
            get {
                object obj = ResourceManager.GetObject("TankImg01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg01I {
            get {
                object obj = ResourceManager.GetObject("TankImg01I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg01II {
            get {
                object obj = ResourceManager.GetObject("TankImg01II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg01III {
            get {
                object obj = ResourceManager.GetObject("TankImg01III", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg01IV {
            get {
                object obj = ResourceManager.GetObject("TankImg01IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg10 {
            get {
                object obj = ResourceManager.GetObject("TankImg10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg10I {
            get {
                object obj = ResourceManager.GetObject("TankImg10I", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg10II {
            get {
                object obj = ResourceManager.GetObject("TankImg10II", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg10III {
            get {
                object obj = ResourceManager.GetObject("TankImg10III", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TankImg10IV {
            get {
                object obj = ResourceManager.GetObject("TankImg10IV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wall {
            get {
                object obj = ResourceManager.GetObject("Wall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
